Adnat/config/routes.rb
Rails.application.routes.draw do
    get 'log_out' => 'sessions#destroy', :as => "log_out"
    get 'log_in' => 'sessions#new', :as => "log_in"
    get 'sign_up' => 'users#new', :as => "sign_up"
    get 'welcome' => 'sessions#welcome', :as => "welcome"
    get 'overview' => 'sessions#overview', :as => "overview"
    put 'leave/:id' => 'users#leave_organisation', :as => "leave_organisation"
    put 'join/:id' => 'users#join_organisation', :as => "join_organisation"

    root :to => "sessions#overview"

    resources :users
    resources :sessions
    resources :organisations
    resources :shifts
end

Adnat/app/models/user.rb
class User < ApplicationRecord
    belongs_to :organisation, optional: true
    has_many :shifts, dependent: :delete_all, inverse_of: :user

    has_secure_password

    validates_confirmation_of :password
    validates_presence_of :password, :on => :create
    validates_presence_of :email_address
    validates_uniqueness_of :email_address
    validates :password, length: { minimum: 6 }, :on => :create
    validates :email_address, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :name, presence: true
end

Adnat/app/controllers/users_controller.rb
class UsersController < ApplicationController

    skip_before_action :authorized, only: [:new, :create]

    def user_params
        params.require(:user).permit(:email_address, :name, :password, :password_confirmation)
    end

    def new
        # new user instance for the form
        @user = User.new
    end

    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to '/welcome', :notice => "Signed up!"
        else
            render "new"
        end
    end

    def edit
        @user = User.find(current_user.id)
    end

    def update
        @user = User.update(current_user.id, user_params)
        if @user.errors.any?
            render "edit"
        else
            if current_user.organisation_id != nil
                redirect_to overview_path
            else
                redirect_to welcome_path
            end
        end
    end

    def join_organisation
        organisation = Organisation.find(params[:id])
        if organisation
            User.update(current_user.id, organisation_id: organisation.id)
            redirect_to overview_path
        end
    end

    def leave_organisation
        User.update(current_user.id, organisation_id: nil)
        redirect_to welcome_path
    end
end

Adnat/app/helpers/users_helper.rb
module UsersHelper
end

Adnat/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Adnat/app/views/users/edit.html.erb
<h2> Edit User </h2>
<%= form_with model: @user, local: true do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
            <h3><font color="red">Form is invalid</font></h3>
            <ul>
                <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :"Name:" %>
        <%= f.text_field :name %><br />
    </p>
    <p>
        <%= f.label :"Email:" %>
        <%= f.text_field :email_address%><br />
    </p>
    <p class="button"><%= f.submit "Update" %></p>
<%end%>

Adnat/app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
        <h3><font color="red">Form is invalid</font></h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :"Name:" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :"Email:" %><br />
    <%= f.text_field :email_address %>
  </p>
  <p>
      <%= f.label :"Password:" %><br />
    <i><%= f.label :minimum, "(6 characters minimum)" %></i><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :"Password Confirmation:" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit "Sign Up" %></p>
  <%= link_to "log in", log_in_path %>
<% end %>