Adnat/config/routes.rb
Rails.application.routes.draw do
    get 'log_out' => 'sessions#destroy', :as => "log_out"
    get 'log_in' => 'sessions#new', :as => "log_in"
    get 'sign_up' => 'users#new', :as => "sign_up"
    get 'welcome' => 'sessions#welcome', :as => "welcome"
    get 'overview' => 'sessions#overview', :as => "overview"
    put 'leave/:id' => 'users#leave_organisation', :as => "leave_organisation"
    put 'join/:id' => 'users#join_organisation', :as => "join_organisation"

    root :to => "sessions#overview"

    resources :users
    resources :sessions
    resources :organisations
    resources :shifts
end

Adnat/app/models/organisation.rb
class Organisation < ApplicationRecord
    has_many :users, dependent: :nullify

    validates :name, presence: true, uniqueness: true
    validates :hourly_rate, numericality: { greater_than_or_equal_to: 0 }
end

Adnat/app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
    def organisation_params
        params.require(:organisation).permit(:name, :hourly_rate)
    end

    def create
        @organisation = Organisation.create(organisation_params)
        if @organisation.save
            User.update(current_user.id, organisation_id: @organisation.id)
            redirect_to overview_path
        else
            render "sessions/welcome"
        end
    end

    def edit
        @organisation = Organisation.find(params[:id])
    end

    def update
        @organisation = Organisation.update(params[:id], organisation_params)
        if @organisation.errors.any?
            render "edit"
        else
            if current_user.organisation_id != nil
                redirect_to overview_path
            else
                redirect_to welcome_path
            end
        end
    end

    def destroy
        Organisation.destroy(params[:id])
        redirect_to welcome_path
    end
end

Adnat/app/helpers/organisations_helper.rb
module OrganisationsHelper
end

Adnat/app/views/organisations/edit.html.erb
<h2> Edit Organisation </h2>
<%= form_with model: @organisation, local: true do |f| %>
    <% if @organisation.errors.any? %>
        <div class="error_messages">
            <h3><font color="red">Form is invalid</font></h3>
            <ul>
                <% for message in @organisation.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        <%= f.label :"Name:" %>
        <%= f.text_field :name %><br />
        <%= f.label :"Hourly rate: $" %>
        <%= f.number_field :hourly_rate, step: :any%> per hour<br />
    </p>
    <p class="button"><%= f.submit "Update" %></p>
<%end%>
<%= link_to "Delete", organisation_path(id: @organisation.id), :method => :delete, data: {confirm: "Are you sure?"} %>