Adnat/config/routes.rb
Rails.application.routes.draw do
    get 'log_out' => 'sessions#destroy', :as => "log_out"
    get 'log_in' => 'sessions#new', :as => "log_in"
    get 'sign_up' => 'users#new', :as => "sign_up"
    get 'welcome' => 'sessions#welcome', :as => "welcome"
    get 'overview' => 'sessions#overview', :as => "overview"
    put 'leave/:id' => 'users#leave_organisation', :as => "leave_organisation"
    put 'join/:id' => 'users#join_organisation', :as => "join_organisation"

    root :to => "sessions#overview"

    resources :users
    resources :sessions
    resources :organisations
    resources :shifts
end

Adnat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adnat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
      th, td {
        padding: 10px;
      }
      td {
        text-align: center;
      }
    </style>
  </head>

  <body>
    <a href="/"><h1>Adnat</h1></a>
    <div id="user_nav">
      <% if current_user %>
        Logged in as <%= current_user.name %>.
        <%= link_to "Log out", log_out_path %>
        <br />
        <%= link_to "Edit", edit_user_path(:id => current_user.id) %> user details.
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </body>
</html>